### PR TITLE
Update BetterCodeHub.md

### PR DESCRIPTION
**Pull request by MichielCuijpers**

### CODE REVIEW

**Comment by jdiazfernandez** [comment]
Thank you @MichielCuijpers 
In a few weeks we'll start to use BCH
In the change I can say you say "Service by SoftwareImprovementGroup.com to evaluate Code Quality inside your CI/CD"  Is there a way/task to automatically triger BCH checks after a push?

**Comment by MichielCuijpers** [comment]
Yes, just click on the pr icon on the card in the bettecodehub portal. Then the owner of the repo will set a webhook that will trigger the analysis for every push and pull request

**Comment by jdiazfernandez** [comment]
Forgive my dismissal. I just remembered. You were configuring that in the organization and I already made those steps with a repository.

**Comment by jdiazfernandez** [comment]
Thank you again @MichielCuijpers

**Pull request merged**
